#############################################################################
# File name:  Makefile
# Author:     chadd williams
# Date:       June 6, 2022
# Class:      CS300
# Assignment: List and Hashtable
# Purpose:    Practice with Data structures!
#############################################################################

#### DO NOT EDIT THIS FILE ####

.PHONY: List Hashtable

all: List # Hashtable

List:
	cd $@; make

Hashtable: List
	cd $@; make

clean:
	cd List; make clean
	cd Hashtable ; make clean

#### DO NOT EDIT THIS FILE ####