#############################################################################
# File name:  Makefile
# Author:     chadd williams
# Date:       Sept 1, 2021
# Class:      CS300
# Assignment: 
# Purpose:    
#############################################################################

CC=clang
CFLAGS=-g -Wall
VALGRIND_FLAGS=-v --leak-check=yes --track-origins=yes --leak-check=full \
--show-leak-kinds=all
ENSCRIPT_FLAGS=-C -T 2 -p - -M Letter --color -fCourier8

TARGETS=bin/tinyDB bin/listtester

all: ${TARGETS}

bin/driverUtil.o: src/driverUtil.c include/driverUtil.h
	${CC} ${CFLAGS} -c -o bin/driverUtil.o src/driverUtil.c 

#### EDIT BELOW THIS LINE
#### EDIT THE COMMENT AT THE TOP TO CONTAIN YOUR NAME


# TODO 
bin/tinyDB:

# TODO 
bin/listtester:




# TODO
printAll:

# TODO
clean:
	
# TODO:
valgrindTinyDB:

# TODO:
valgrindTester:
